# fly -t main set-pipeline -p docker-login-pipeline -c hublogin.yml
# fly -t main set-pipeline -p docker-login-pipeline -c hublogin.yml --load-vars-from=secrets.yml
# fly -t main set-pipeline -p docker-login-pipeline -c hublogin.yml --var "USERNAME=nitinneet23@gmail.com" --var "PASSWORD=2310shurlinitin"
# fly -t main trigger-job -j docker-login-pipeline/docker-login -v "docker-username=nitinneet23@gmail.com" -v "docker-password=2310shurlinitin"

# fly -t main unpause-pipeline -p docker-login-pipeline
# fly -t main trigger-job -j docker-login-pipeline/docker-login

jobs:
- name: docker-login
  plan:
  - task: login
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: docker, tag: stable}
      params:
        USERNAME: nitinneet23@gmail.com
        PASSWORD: 2310shurlinitin
      run:
        path: /bin/sh
        args:
          - -exc
          - |
            echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
